### PR TITLE
Update link to OpenAg MVP

### PR DESCRIPTION
**Pull request by mesejo**
The link to the OpenAg MVP is broken. Added a possible alternative

### CODE REVIEW

**Comment by ic** [comment]
Thank you for your update! It seems the link you chose is superseded by [MVP III](https://github.com/futureag/mvp). Do you know which is best, or we just take the latest one? It seems III goes a bit further.

**Comment by mesejo** [comment]
> Thank you for your update! It seems the link you chose is superseded by [MVP III](https://github.com/futureag/mvp). Do you know which is best, or we just take the latest one? It seems III goes a bit further.

I'll said let's use [MVP III](https://github.com/futureag/mvp) as the one I wrote in the commit is fork from this one. What do you think?

**Comment by mesejo** [comment]
@ic Thanks for the feedback! Just now I got the time for updating the link.

**Comment by ic** [comment]
Thank you very much for the update! And my apologies for the belated merge. All the best!

**Pull request merged**
